### ISSUE TITLE
Healthkits/Vials, batteries, some props and footsteps [Windows]

### ISSUE THREAD

**Issue by hssavant** [speedvoltage/hl2dm-bugfix#5]
I've noticed that, on Windows, while batteries are able to be touched and consumed, the armor doesn't actually reflect on the hud. With this, healthkits and vials can't be touched/consumed whatsoever, and various props are able to be simply walked through like the computer/monitor on lockdown.

I've also noticed that footsteps can't be heard until sv_footsteps is set to 1 using an sa command. This must be done every map, even if the cvar is set in a server.cfg.

All issues present in 1.2.2 as well as 1.2.3

**Comment by speedvoltage** [comment]
I cannot reproduce any of the issues above.
https://streamable.com/vzwynb
https://streamable.com/aae0lm
https://streamable.com/c0xotf

> I've noticed that, on Windows, while batteries are able to be touched and consumed, the armor doesn't actually reflect on the hud. 

The only thing I can think of is to check that this line exists in `skill.cfg` or `server.cfg`:
```sk_battery			"15"```

> With this, healthkits and vials can't be touched/consumed whatsoever, and various props are able to be simply walked through like the computer/monitor on lockdown.

All the collisions work fine on my end and kits can be picked up just fine, and their sounds are even fixed.

> I've also noticed that footsteps can't be heard until sv_footsteps is set to 1 using an sa command. This must be done every map, even if the cvar is set in a server.cfg.

Should not have to do this and I did not have to. `sv_footsteps` is set to 0 because there is hacky implementation to make footstep sounds server-side to fix missing footstep sounds client-side.

Everything is running fine on my end running SRCDS on both Windows and Linux (Debian 12). I re-created an instance of SRCDS and downloaded a copy of the files I uploaded here on the off-chance I might have forgot something, but it still worked fine, although I noticed some leftover files that needed to be removed.

Have you installed the whole package? Do you run the binaries alone or do you have Metamod: Source and Sourcemod installed?

**Comment by hssavant** [comment]
Yea, I'm running the binaries without SM just to be safe for now.. reinstalling the script files in the hl2 directory solved the footsteps issue. I was running hl in the [previous_build] to get this to work, and after reinstalling the package, I was then told the server was running a newer version of the game, so I switched to [beta] and am able to connect.. The sk_battery line is in the skill config, but the issues persist.. It must be SRCDS related

**Comment by speedvoltage** [comment]
The game itself does not need to be in any beta, but SRCDS does need to be in **prerelease**. Is it the case?

**Comment by hssavant** [comment]
Ok, no longer on beta, still able to connect. attempted to app_update to prerelease, but it was already up to date. It's still happening though, I even verified the integrity of my own game files

**Comment by speedvoltage** [comment]
To ensure it really is, have steamcmd generate a new SRCDS instance in a new path, then `app_update 232370 -beta prerelease validate`. None of us here are able to reproduce the issue above, so we can safely assume the issue is local.

**Comment by hssavant** [comment]
That seems to have solved the issue. My apologies.

**Comment by speedvoltage** [comment]
Glad everything works! Let me know if run into more issues.
